-- ABSENCE

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(1, 2, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(1, 3, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(1, 6, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(2, 12, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(2, 16, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(3, 22, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(3, 24, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(4, 32, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(4, 36, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(5, 40, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(5, 43, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(5, 44, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(6, 48, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(6, 49, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(6, 51, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(6, 52, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(7, 55, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(7, 56, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(8, 63, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(8, 65, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(8, 66, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(9, 71, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(9, 73, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(9, 74, 0.50, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(10, 78, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(10, 79, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(11, 85, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(11, 86, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(11, 88, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(12, 92, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(12, 93, 0.50, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(13, 97, 0.50, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(13, 99, 0.50, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(13, 100, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(13, 101, 1.00, 1)


-- GRADE

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 1, 1)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 4, 1, 1)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 1, 2)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 3, 1, 3)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 3, 1, 8)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 4, 1, 9)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 1, 2, 9)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 1, 2, 1)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 1, 2, 4)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 2, 3, 12)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 3, 13)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 4, 3, 17)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 4, 3, 18)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 2, 2, 22)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 2, 2, 24)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 2, 24)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 8, 1, 24)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 8, 1, 25)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 8, 5, 32)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 1, 3, 32)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 7, 33)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 8, 33)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 3, 6, 37)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 3, 6, 40)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 3, 10, 41)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 4, 41)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 4, 2, 41)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 1, 47)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 2, 1, 48)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 3, 1, 50)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 3, 9, 50)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 3, 7, 50)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 11, 52)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 1, 55)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 3, 1, 56)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 2, 56)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 3, 56)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(3.00, 1, 4, 57)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 2, 4, 57)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 1, 1, 64)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 1, 64)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 3, 4, 64)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 7, 65)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 2, 8, 66)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 8, 13, 66)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 12, 67)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 2, 71)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 3, 2, 72)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 3, 4, 75)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 3, 4, 76)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 6, 74)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 6, 78)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 7, 78)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 1, 78)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 1, 7, 79)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 1, 3, 79)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 1, 3, 80)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(3.00, 1, 1, 80)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 1, 1, 81)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 1, 1, 85)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 1, 2, 88)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 1, 3, 88)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 5, 89)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 4, 10, 90)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 4, 1, 91)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 4, 1, 92)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 1, 92)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 2, 1, 93)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 1, 94)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 2, 9, 94)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(3.00, 2, 8, 96)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 5, 97)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 5, 97)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 1, 99)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 4, 1, 100)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 4, 2, 101)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 13, 102)