-- LESSON

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '28-10-2022', 105), CONVERT(TIME, '7:30'), CONVERT(TIME, '8:10'), 1)

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '28-10-2022', 105), CONVERT(TIME, '7:30'), CONVERT(TIME, '8:10'), 11)

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '28-10-2022', 105), CONVERT(TIME, '9:10'), CONVERT(TIME, '9:50'), 12)

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '31-10-2022', 105), CONVERT(TIME, '10:00'), CONVERT(TIME, '10:40'), 2)

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '31-10-2022', 105), CONVERT(TIME, '10:00'), CONVERT(TIME, '10:40'), 3)

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '31-10-2022', 105), CONVERT(TIME, '11:00'), CONVERT(TIME, '11:40'), 4)

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '31-10-2022', 105), CONVERT(TIME, '11:00'), CONVERT(TIME, '11:40'), 9)


-- ABSENCE

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(14, 2, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(14, 4, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(14, 7, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(15, 12, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(15, 16, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(16, 22, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(16, 25, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(17, 32, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(17, 36, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(18, 40, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(18, 43, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(18, 44, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(19, 48, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(19, 49, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(19, 51, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(19, 52, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(20, 55, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(20, 56, 1.00, 1)