-- TEACHER

INSERT INTO TEACHER(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, PHONE, EMAIL, SUBJECT_ID, SCHOOL_ID)
VALUES('ivanka_ivanova', 'ivanova_password', 'Иванка', 'Петрова', 'Иванова', 'F', '0889333111', 'ivanka_ivanova@gmail.com', 2, 2)

INSERT INTO TEACHER(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, PHONE, EMAIL, SUBJECT_ID, SCHOOL_ID)
VALUES('magi_petrova', 'petrova_password', 'Маги', 'Константинова', 'Петрова', 'F', '0833545678', 'm_petrova@gmail.com', 1, 2)

INSERT INTO TEACHER(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, PHONE, EMAIL, SUBJECT_ID, SCHOOL_ID)
VALUES('martin_kostadinov', 'kostadinov_password', 'Мартин', 'Миленов', 'Костадинов', 'M', '0844226745', 'm_kostadinov@gmail.com', 3, 2)


-- LESSON

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '26-10-2022', 105), CONVERT(TIME, '7:30'), CONVERT(TIME, '8:10'), 19)

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '26-10-2022', 105), CONVERT(TIME, '7:30'), CONVERT(TIME, '8:10'), 20)

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '26-10-2022', 105), CONVERT(TIME, '9:10'), CONVERT(TIME, '9:50'), 21)


-- CLASS

INSERT INTO CLASS(CLASS_NUMBER, CLASS_LETTER, SCHOOL_ID, TEACHER_ID)
VALUES(5, 'А', 2, 20)

INSERT INTO CLASS(CLASS_NUMBER, CLASS_LETTER, SCHOOL_ID, TEACHER_ID)
VALUES(5, 'Б', 2, 19)

INSERT INTO CLASS(CLASS_NUMBER, CLASS_LETTER, SCHOOL_ID, TEACHER_ID)
VALUES(5, 'В', 2, 21)


-- STUDENT

-- 5А

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('todor_mihailov', 'mihailov_password', 'Тодор', 'Мартинов', 'Михаилов', 'M', CONVERT(DATE, '20-05-2011', 105), 'София', NULL, NULL, 14)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('georgi_evstatiev', 'evstatiev_password', 'Георги', 'Петков', 'Евстатиев', 'M', CONVERT(DATE, '14-07-2011', 105), 'София', '0892233458', 'georgi_evstatiev@gmail.com', 14)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('iva_dimitrova', 'dimitrova_password', 'Ива', 'Петрова', 'Димитрова', 'F', CONVERT(DATE, '07-06-2011', 105), 'София', '0855222118', 'iva_dimitrova@gmail.com', 14)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('sava_popov', 'popov_password', 'Сава', 'Иванов', 'Попов', 'M', CONVERT(DATE, '12-09-2011', 105), 'София', '0822111045', NULL, 14)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('sashka_petkova', 'petkova_password', 'Сашка', 'Петрова', 'Петкова', 'F', CONVERT(DATE, '28-09-2011', 105), 'София', '0811144777', 'sashka_petkova@gmail.com', 14)


-- 5Б

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('marti_kostov', 'kostov_password', 'Марти', 'Иванов', 'Костов', 'M', CONVERT(DATE, '09-07-2011', 105), 'София', NULL, NULL, 15)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('geri_nikolova', 'nikolova_password', 'Гери', 'Спасова', 'Николова', 'F', CONVERT(DATE, '03-09-2011', 105), 'София', '0822567444', 'geri_nikolova@gmail.com', 15)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('petar_hristov', 'hristov_password', 'Петър', 'Иванов', 'Христов', 'M', CONVERT(DATE, '17-07-2006', 105), 'София', NULL, NULL, 15)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('galina_veleva', 'veleva_password', 'Галина', 'Константинова', 'Велева', 'F', CONVERT(DATE, '19-07-2011', 105), 'София', '0882669444', 'galina_veleva@gmail.com', 15)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('monika_dimova', 'dimova_password', 'Моника', 'Петрова', 'Димова', 'F', CONVERT(DATE, '23-08-2011', 105), 'София', NULL, 'monika_dimova@gmail.com', 15)


-- 5В

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('sasho_kostov', 'kostov_password', 'Сашо', 'Иванов', 'Костов', 'M', CONVERT(DATE, '19-07-2011', 105), 'София', NULL, NULL, 16)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('galina_nikolova', 'nikolova_password', 'Галина', 'Спасова', 'Николова', 'F', CONVERT(DATE, '23-09-2011', 105), 'София', '0811567444', 'galina_nikolova@gmail.com', 16)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('pencho_hristov', 'hristov_password', 'Пенчо', 'Иванов', 'Христов', 'M', CONVERT(DATE, '27-07-2006', 105), 'София', NULL, NULL, 16)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('petya_veleva', 'veleva_password', 'Петя', 'Константинова', 'Велева', 'F', CONVERT(DATE, '29-07-2011', 105), 'София', '0833469444', 'petya_veleva@gmail.com', 16)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('didi_dimova', 'dimova_password', 'Диди', 'Петрова', 'Димова', 'F', CONVERT(DATE, '13-06-2011', 105), 'София', NULL, 'didi_dimova@gmail.com', 16)


-- ABSENCE

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(21, 104, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(21, 105, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(21, 106, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(22, 108, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(22, 110, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(22, 111, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(23, 114, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(23, 115, 0.50, 0)


-- GRADE

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 1, 104)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 1, 105)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 1, 104)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 2, 107)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 2, 105)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 2, 110)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 1, 111)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 3, 3, 112)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 13, 109)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 3, 2, 113)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 3, 2, 114)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 1, 117)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(3.00, 2, 3, 115)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 5, 2, 115)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 7, 3, 114)