-- TEACHER

INSERT INTO TEACHER(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, PHONE, EMAIL, SUBJECT_ID, SCHOOL_ID)
VALUES('marinka_ivanova', 'ivanova_password', 'Маринка', 'Петканова', 'Иванова', 'F', '0882223144', 'marinka_ivanova@gmail.com', 1, 3)

INSERT INTO TEACHER(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, PHONE, EMAIL, SUBJECT_ID, SCHOOL_ID)
VALUES('geri_petrova', 'petrova_password', 'Гери', 'Константинова', 'Петрова', 'F', '0899625678', 'g_petrova@gmail.com', 2, 3)

INSERT INTO TEACHER(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, PHONE, EMAIL, SUBJECT_ID, SCHOOL_ID)
VALUES('sasho_kostadinov', 'kostadinov_password', 'Сашо', 'Миленов', 'Костадинов', 'M', '0811996745', 'sasho_kostadinov@gmail.com', 3, 3)


-- LESSON

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '31-10-2022', 105), CONVERT(TIME, '7:30'), CONVERT(TIME, '8:10'), 34)

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '31-10-2022', 105), CONVERT(TIME, '7:30'), CONVERT(TIME, '8:10'), 35)

INSERT INTO LESSON([DATE], START_TIME, END_TIME, TEACHER_ID)
VALUES(CONVERT(DATE, '31-10-2022', 105), CONVERT(TIME, '9:10'), CONVERT(TIME, '9:50'), 36)


-- CLASS

INSERT INTO CLASS(CLASS_NUMBER, CLASS_LETTER, SCHOOL_ID, TEACHER_ID)
VALUES(1, 'А', 3, 34)

INSERT INTO CLASS(CLASS_NUMBER, CLASS_LETTER, SCHOOL_ID, TEACHER_ID)
VALUES(2, 'A', 3, 35)


-- STUDENT

-- 1А

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('toma_mihailov', 'mihailov_password', 'Тома', 'Мартинов', 'Михаилов', 'M', CONVERT(DATE, '20-05-2015', 105), 'Пловдив', NULL, NULL, 17)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('marko_hristev', 'hristev_password', 'Марко', 'Петков', 'Христев', 'M', CONVERT(DATE, '14-07-2015', 105), 'Пловдив', '0822733458', 'marko_hristev@gmail.com', 17)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('ina_dimitrova', 'dimitrova_password', 'Ина', 'Петрова', 'Димитрова', 'F', CONVERT(DATE, '07-06-2015', 105), 'Пловдив', '0844882118', 'ina_dimitrova@gmail.com', 17)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('angel_popov', 'popov_password', 'Ангел', 'Иванов', 'Попов', 'M', CONVERT(DATE, '15-09-2015', 105), 'Пловдив', '0815111045', NULL, 17)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('sara_petkova', 'petkova_password', 'Сара', 'Петрова', 'Петкова', 'F', CONVERT(DATE, '21-09-2015', 105), 'Пловдив', '0811142227', 'sara_petkova@gmail.com', 17)


-- 2А

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('filip_mihailov', 'mihailov_password', 'Филип', 'Мартинов', 'Михаилов', 'M', CONVERT(DATE, '25-05-2014', 105), 'Пловдив', NULL, NULL, 18)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('mihail_hristev', 'hristev_password', 'Михаил', 'Петков', 'Христев', 'M', CONVERT(DATE, '11-07-2014', 105), 'Пловдив', '0844533458', 'mihail_hristev@gmail.com', 18)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('stefka_dimitrova', 'dimitrova_password', 'Стефка', 'Петрова', 'Димитрова', 'F', CONVERT(DATE, '09-06-2014', 105), 'Пловдив', '0844117118', 'stefka_dimitrova@gmail.com', 18)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('anastas_popov', 'popov_password', 'Анастас', 'Иванов', 'Попов', 'M', CONVERT(DATE, '13-09-2014', 105), 'Пловдив', '0822711045', NULL, 18)

INSERT INTO STUDENT(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, BIRTH_DATE, BIRTH_PLACE, PHONE, EMAIL, CLASS_ID)
VALUES('sevdalina_petkova', 'petkova_password', 'Севдалина', 'Петрова', 'Петкова', 'F', CONVERT(DATE, '13-09-2014', 105), 'Пловдив', '0877143527', 'sevdalina_petkova@gmail.com', 18)


-- ABSENCE

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(24, 118, 1.00, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(24, 120, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(24, 121, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(25, 123, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(25, 124, 0.50, 0)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(25, 126, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(26, 119, 1.00, 1)

INSERT INTO ABSENCE(LESSON_ID, STUDENT_ID, ABSENCE_AMOUNT, IS_EXCUSED)
VALUES(26, 120, 0.50, 0)


-- GRADE

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 1, 120)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 1, 121)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 1, 124)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 6, 2, 118)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 2, 119)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 2, 119)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 1, 126)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 3, 3, 127)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 3, 13, 125)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(4.00, 3, 2, 118)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(5.00, 3, 2, 121)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 1, 123)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(3.00, 2, 3, 127)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 3, 126)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 2, 1, 124)

INSERT INTO GRADE(GRADE_VALUE, GRADE_TYPE_ID, SUBJECT_ID, STUDENT_ID)
VALUES(6.00, 7, 14, 124)