-- Функция, която извежда среден успех по вид изпитване в системата.

CREATE FUNCTION TYPE_AVERAGE_GRADE(@TYPE_ID INT) RETURNS VARCHAR(200)
AS
BEGIN
DECLARE @TYPE_NAME VARCHAR(50), @AVG_GRADE NUMERIC(3,2)
SELECT @TYPE_NAME = GRADE_TYPE_NAME, @AVG_GRADE = AVG(GRADE_VALUE)
FROM GRADE_TYPE GT JOIN GRADE G
ON GT.GRADE_TYPE_ID = G.GRADE_TYPE_ID 
WHERE GT.GRADE_TYPE_ID = @TYPE_ID
GROUP BY GT.GRADE_TYPE_ID, GRADE_TYPE_NAME
RETURN @TYPE_NAME + ' (ID = ' + CAST(@TYPE_ID AS VARCHAR) + '), среден успех: ' + CAST(@AVG_GRADE AS VARCHAR) + '.'
END

SELECT DBO.TYPE_AVERAGE_GRADE(GRADE_TYPE_ID) AS TYPE_AVERAGE_GRADE_RESULT
FROM GRADE_TYPE


-- Функция, която извежда среден успех по вид предмет в системата.

CREATE FUNCTION SUBJECT_AVERAGE_GRADE(@SUBJ_ID INT) RETURNS VARCHAR(200)
AS
BEGIN
DECLARE @SUBJ_NAME VARCHAR(50), @AVG_GRADE NUMERIC(3,2)
SELECT @SUBJ_NAME = SUBJECT_NAME, @AVG_GRADE = AVG(GRADE_VALUE)
FROM GRADE G JOIN [SUBJECT] S
ON G.SUBJECT_ID = S.SUBJECT_ID
WHERE S.SUBJECT_ID = @SUBJ_ID
GROUP BY S.SUBJECT_ID, SUBJECT_NAME
RETURN @SUBJ_NAME + ' (ID = ' + CAST(@SUBJ_ID AS VARCHAR) + '), среден успех: ' + CAST(@AVG_GRADE AS VARCHAR) + '.'
END

SELECT DBO.SUBJECT_AVERAGE_GRADE(SUBJECT_ID) AS SUBJECT_AVERAGE_GRADE_RESULT
FROM [SUBJECT]


-- Функция, която извежда среден успех по всички предмети в дадено училище в съответния град.

CREATE FUNCTION SCHOOL_GRADE(@SCH_ID INT) RETURNS VARCHAR(200)
AS
BEGIN
DECLARE @SCH_NAME VARCHAR(50), @SCH_CITY VARCHAR(50), @AVG_GRADE NUMERIC(3,2)
SELECT @SCH_NAME = SCHOOL_NAME, @SCH_CITY = CITY, @AVG_GRADE = AVG(GRADE_VALUE)
FROM SCHOOL S JOIN [ADDRESS] A
ON S.ADDRESS_ID = A.ADDRESS_ID
JOIN CLASS C
ON S.SCHOOL_ID = C.SCHOOL_ID
JOIN STUDENT ST
ON ST.CLASS_ID = C.CLASS_ID
JOIN GRADE G
ON G.STUDENT_ID = ST.STUDENT_ID
WHERE S.SCHOOL_ID = @SCH_ID
GROUP BY S.SCHOOL_ID, SCHOOL_NAME, CITY
RETURN @SCH_NAME + ' (ID = ' + CAST(@SCH_ID AS VARCHAR) + '), град ' + CAST(@SCH_CITY AS VARCHAR)
+ ', среден успех: '  + CAST(@AVG_GRADE AS VARCHAR) + '.'
END

SELECT DBO.SCHOOL_GRADE(SCHOOL_ID) AS SCHOOL_GRADE_RESULT
FROM SCHOOL


-- Функция, която извежда сума от отсъствията в дадено училище в съответния град.

CREATE FUNCTION SCHOOL_ABSENCE(@SCH_ID INT) RETURNS VARCHAR(200)
AS
BEGIN
DECLARE @SCH_NAME VARCHAR(50), @SCH_CITY VARCHAR(50), @ABS_AMOUNT NUMERIC(6,2)
SELECT @SCH_NAME = SCHOOL_NAME, @SCH_CITY = CITY, @ABS_AMOUNT = SUM(ABSENCE_AMOUNT)
FROM SCHOOL S JOIN [ADDRESS] A
ON S.ADDRESS_ID = A.ADDRESS_ID
JOIN CLASS C
ON S.SCHOOL_ID = C.SCHOOL_ID
JOIN STUDENT ST
ON ST.CLASS_ID = C.CLASS_ID
JOIN ABSENCE AB
ON AB.STUDENT_ID = ST.STUDENT_ID
WHERE S.SCHOOL_ID = @SCH_ID
GROUP BY S.SCHOOL_ID, SCHOOL_NAME, CITY
RETURN @SCH_NAME + ' (ID = ' + CAST(@SCH_ID AS VARCHAR) + '), град ' + CAST(@SCH_CITY AS VARCHAR)
+ ', брой отсъствия: ' + CAST(@ABS_AMOUNT AS VARCHAR) + '.'
END

SELECT DBO.SCHOOL_ABSENCE(SCHOOL_ID) AS SCHOOL_ABSENCE_RESULT
FROM SCHOOL


-- Функция, която извежда имената на преподавателите, техния предмет и даденото училище в съответния град.

CREATE FUNCTION TEACHER_SUBJECT_SCHOOL() RETURNS TABLE
AS
RETURN
SELECT FIRST_NAME, LAST_NAME, SUBJECT_NAME, SCHOOL_NAME, CITY
FROM TEACHER T JOIN [SUBJECT] S
ON T.SUBJECT_ID = S.SUBJECT_ID
JOIN SCHOOL SC
ON SC.SCHOOL_ID = T.SCHOOL_ID
JOIN [ADDRESS] A
ON A.ADDRESS_ID = SC.ADDRESS_ID

SELECT *
FROM DBO.TEACHER_SUBJECT_SCHOOL() ORDER BY FIRST_NAME, LAST_NAME