-- Процедура, която извежда броя на учениците в класовете на дадено училище в съответния град.

CREATE PROCEDURE CLASS_STUDENTS
AS
SELECT CLASS_NUMBER, CLASS_LETTER, SCHOOL_NAME, CITY, COUNT(STUDENT_ID) AS STUDENT_COUNT
FROM STUDENT ST JOIN CLASS C
ON ST.CLASS_ID = C.CLASS_ID
JOIN SCHOOL SC
ON SC.SCHOOL_ID = C.SCHOOL_ID
JOIN ADDRESS A
ON A.ADDRESS_ID = SC.ADDRESS_ID
GROUP BY CLASS_NUMBER, CLASS_LETTER, SCHOOL_NAME, CITY

EXEC CLASS_STUDENTS


-- Процедура, която връща като параметри броя нанесени оценки и среден успех по даден предмет в системата с идентификатор, подаден като входен параметър.

CREATE PROCEDURE GET_SUBJECT_TOTAL @SUBJ_ID INT, @GRADE_COUNT INT OUTPUT, @GRADE_AVERAGE NUMERIC(3,2) OUTPUT
AS
SELECT @GRADE_COUNT = COUNT(GRADE_ID)
FROM GRADE G JOIN SUBJECT S
ON G.SUBJECT_ID = S.SUBJECT_ID
WHERE S.SUBJECT_ID = @SUBJ_ID
SELECT @GRADE_AVERAGE = AVG(GRADE_VALUE)
FROM GRADE G JOIN SUBJECT S
ON G.SUBJECT_ID = S.SUBJECT_ID
WHERE S.SUBJECT_ID = @SUBJ_ID

DECLARE @GR_COUNT INT, @GR_AVERAGE NUMERIC(3,2)
EXEC GET_SUBJECT_TOTAL 1, @GR_COUNT OUTPUT, @GR_AVERAGE OUTPUT
PRINT 'Брой оценки: ' + CAST(@GR_COUNT AS VARCHAR)
PRINT 'Среден успех: ' + CAST(@GR_AVERAGE AS VARCHAR)


-- Процедура, която извежда броя на преподавателите в дадено училище в съответния град.

CREATE PROCEDURE TEACHERS_SCHOOL
AS
SELECT SCHOOL_NAME, CITY, COUNT(TEACHER_ID) AS TEACHER_COUNT
FROM TEACHER T JOIN SCHOOL SC
ON T.SCHOOL_ID = SC.SCHOOL_ID
JOIN [ADDRESS] A
ON A.ADDRESS_ID = SC.ADDRESS_ID
GROUP BY SCHOOL_NAME, CITY

EXEC TEACHERS_SCHOOL


-- Процедура, която извежда класовете с техните класни ръководители в дадено училище в съответния град.

CREATE PROCEDURE CLASSES_LEAD_TEACHER
AS
SELECT CLASS_NUMBER, CLASS_LETTER, FIRST_NAME, LAST_NAME, SCHOOL_NAME, CITY
FROM CLASS C JOIN SCHOOL SC
ON C.SCHOOL_ID = SC.SCHOOL_ID
JOIN TEACHER T
ON T.TEACHER_ID = C.TEACHER_ID
JOIN [ADDRESS] A
ON A.ADDRESS_ID = SC.ADDRESS_ID

EXEC CLASSES_LEAD_TEACHER