CREATE TABLE TEACHER_HISTORY
(
	CHANGE_ID INT IDENTITY(1,1) PRIMARY KEY,
	TEACHER_ID INT NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	MIDDLE_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	GENDER CHAR(1) NOT NULL CHECK (GENDER IN ('F', 'M')),
	PHONE VARCHAR(10),
	EMAIL VARCHAR(50),
    	UPDATED_ON DATETIME NOT NULL,
    	OPERATION CHAR(3) NOT NULL,
    	CHECK(OPERATION = 'INS' OR OPERATION = 'DEL')
)


CREATE TRIGGER TRG_TEACHER_HIST
ON TEACHER
AFTER INSERT, DELETE
AS
BEGIN
    SET NOCOUNT ON
    INSERT INTO TEACHER_HISTORY
    (
	TEACHER_ID,
    	FIRST_NAME,
    	MIDDLE_NAME,
    	LAST_NAME,
	GENDER,
	PHONE,
	EMAIL,
    	UPDATED_ON, 
    	OPERATION
    )
    SELECT
    	I.TEACHER_ID,
	FIRST_NAME,
	MIDDLE_NAME,
    	LAST_NAME,
	GENDER,
	PHONE,
	I.EMAIL,
    	GETDATE(),
    	'INS'
    FROM
        INSERTED I
    UNION ALL
    SELECT
    	D.TEACHER_ID,
    	FIRST_NAME,
    	MIDDLE_NAME,
    	LAST_NAME,
	GENDER,
	PHONE,
	D.EMAIL,
    	GETDATE(),
    	'DEL'
    FROM
        DELETED D
END


SELECT * FROM TEACHER_HISTORY

INSERT INTO TEACHER(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, PHONE, EMAIL, SUBJECT_ID, SCHOOL_ID)
VALUES('kali_todorova', 'todorova_password', 'Кали', 'Христова', 'Тодорова', 'F', NULL, 'kali_todorova@gmail.com', 1, 1)

INSERT INTO TEACHER(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, PHONE, EMAIL, SUBJECT_ID, SCHOOL_ID)
VALUES('marinka_todorova', 'todorova_password', 'Маринка', 'Петкова', 'Тодорова', 'F', '0833227488', 'marinka_todorova@gmail.com', 3, 1)

SELECT * FROM TEACHER_HISTORY

DELETE FROM TEACHER WHERE TEACHER_ID = 31

SELECT * FROM TEACHER_HISTORY

INSERT INTO TEACHER(USERNAME, [PASSWORD], FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, PHONE, EMAIL, SUBJECT_ID, SCHOOL_ID)
VALUES('tanya_tomova', 'tomova_password', 'Таня', 'Петрова', 'Томова', 'F', NULL, NULL, 3, 1)

SELECT * FROM TEACHER_HISTORY